# Generated by Django 5.2.13 on 2026-04-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_scheduleslot_slot_valid_by_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, max_length=80, verbose_name='роль'),
        ),
    ]
