# Generated by Django 5.2.13 on 2026-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='event_type',
            field=models.CharField(blank=True, choices=[('practice', 'Практика'), ('scrim', 'Scrim'), ('vod_review', 'VOD Review'), ('match', 'Матч')], default='', max_length=24, verbose_name='тип события'),
        ),
    ]
