# Generated by Django 5.2.13 on 2026-04-27 12:35

from django.db import migrations, models


def seed_day_event_types(apps, schema_editor):
    ScheduleSlot = apps.get_model('scheduler', 'ScheduleSlot')
    DayEventType = apps.get_model('scheduler', 'DayEventType')

    for day_of_week in range(7):
        event_type = (
            ScheduleSlot.objects
            .filter(day_of_week=day_of_week)
            .exclude(event_type='')
            .order_by('id')
            .values_list('event_type', flat=True)
            .first()
        ) or ''
        DayEventType.objects.update_or_create(
            day_of_week=day_of_week,
            defaults={'event_type': event_type},
        )


def restore_slot_event_types(apps, schema_editor):
    ScheduleSlot = apps.get_model('scheduler', 'ScheduleSlot')
    DayEventType = apps.get_model('scheduler', 'DayEventType')

    for day_event in DayEventType.objects.exclude(event_type=''):
        ScheduleSlot.objects.filter(
            day_of_week=day_event.day_of_week,
            slot_type='available',
        ).update(event_type=day_event.event_type)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_scheduleslot_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='день недели')),
                ('event_type', models.CharField(blank=True, choices=[('', 'Без события'), ('practice', 'Практика'), ('scrim', 'Scrim'), ('vod_review', 'VOD Review'), ('match', 'Матч')], default='', max_length=24, verbose_name='тип события')),
            ],
            options={
                'verbose_name': 'тип события дня',
                'verbose_name_plural': 'типы событий по дням',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.RunPython(seed_day_event_types, restore_slot_event_types),
        migrations.RemoveField(
            model_name='scheduleslot',
            name='event_type',
        ),
    ]
