# Generated by Django 5.2.13 on 2026-04-28 13:05

from django.db import migrations, models


def remap_day_event_types(apps, schema_editor):
    DayEventType = apps.get_model('scheduler', 'DayEventType')
    mapping = {
        'practice': 'competitive',
        'scrim': 'scrim',
        'vod_review': 'review',
        'match': 'tournament',
    }

    for old_value, new_value in mapping.items():
        DayEventType.objects.filter(event_type=old_value).update(event_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_dayeventtype_remove_scheduleslot_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='battle_tags',
            field=models.TextField(blank=True, help_text='Указывайте по одному BattleTag на строку.', verbose_name='battle tags'),
        ),
        migrations.AddField(
            model_name='player',
            name='discord_tag',
            field=models.CharField(blank=True, max_length=120, verbose_name='discord тег'),
        ),
        migrations.RunPython(remap_day_event_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dayeventtype',
            name='event_type',
            field=models.CharField(blank=True, choices=[('', 'Без события'), ('tournament', 'Турнир'), ('scrim', 'Скрим'), ('competitive', 'Компетитив'), ('review', 'Разбор игр')], default='', max_length=24, verbose_name='тип события'),
        ),
    ]
