# Generated by Django 5.2.13 on 2026-04-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_staffmember_alter_player_options_player_role_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='slot_valid_by_type',
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='slot_type',
            field=models.CharField(choices=[('available', 'Диапазон времени'), ('full_day_available', 'Свободен весь день'), ('unavailable', 'Не могу в этот день')], default='available', max_length=24, verbose_name='тип записи'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time_minutes__gt', models.F('start_time_minutes')), ('end_time_minutes__gte', 60), ('end_time_minutes__isnull', False), ('end_time_minutes__lte', 1440), ('slot_type', 'available'), ('start_time_minutes__gte', 0), ('start_time_minutes__isnull', False), ('start_time_minutes__lte', 1380)), models.Q(('end_time_minutes__isnull', True), ('slot_type', 'full_day_available'), ('start_time_minutes__isnull', True)), models.Q(('end_time_minutes__isnull', True), ('slot_type', 'unavailable'), ('start_time_minutes__isnull', True)), _connector='OR'), name='slot_valid_by_type'),
        ),
    ]
