# Generated by Django 5.2.13 on 2026-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_remove_scheduleslot_slot_valid_by_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week_start', models.DateField(blank=True, null=True, verbose_name='текущая неделя')),
                ('last_reset_at', models.DateTimeField(blank=True, null=True, verbose_name='последний сброс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'состояние расписания',
                'verbose_name_plural': 'состояние расписания',
            },
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='slot_valid_by_type',
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='slot_type',
            field=models.CharField(choices=[('available', 'Диапазон времени'), ('full_day_available', 'Свободен весь день'), ('tentative', 'Не уверен'), ('unavailable', 'Не могу в этот день')], default='available', max_length=24, verbose_name='тип записи'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time_minutes__gt', models.F('start_time_minutes')), ('end_time_minutes__gte', 60), ('end_time_minutes__isnull', False), ('end_time_minutes__lte', 1440), ('slot_type', 'available'), ('start_time_minutes__gte', 0), ('start_time_minutes__isnull', False), ('start_time_minutes__lte', 1380)), models.Q(('end_time_minutes__isnull', True), ('slot_type', 'full_day_available'), ('start_time_minutes__isnull', True)), models.Q(('end_time_minutes__isnull', True), ('slot_type', 'tentative'), ('start_time_minutes__isnull', True)), models.Q(('end_time_minutes__isnull', True), ('slot_type', 'unavailable'), ('start_time_minutes__isnull', True)), _connector='OR'), name='slot_valid_by_type'),
        ),
    ]
