# Generated by Django 5.2.13 on 2026-04-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_staffmember_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(max_length=32, unique=True, verbose_name='discord user id')),
                ('username', models.CharField(max_length=80, verbose_name='discord username')),
                ('global_name', models.CharField(blank=True, max_length=80, verbose_name='discord global name')),
                ('avatar_hash', models.CharField(blank=True, max_length=120, verbose_name='discord avatar hash')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='подключено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_connection', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'подключение Discord',
                'verbose_name_plural': 'подключения Discord',
            },
        ),
    ]
