# Generated by Django 5.2.13 on 2026-05-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_gameupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverwatchStatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_tag', models.CharField(blank=True, max_length=120, verbose_name='battle tag')),
                ('overfast_player_id', models.CharField(blank=True, max_length=120, verbose_name='overfast player id')),
                ('mode', models.CharField(choices=[('competitive', 'Competitive'), ('quickplay', 'Quickplay')], max_length=20, verbose_name='режим')),
                ('status', models.CharField(choices=[('ready', 'Готово'), ('error', 'Ошибка'), ('missing_battletag', 'BattleTag не указан')], default='error', max_length=32, verbose_name='статус')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='ошибка')),
                ('summary_json', models.JSONField(blank=True, default=dict, verbose_name='summary json')),
                ('stats_json', models.JSONField(blank=True, default=dict, verbose_name='stats json')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='обновлено')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overwatch_stats_cache', to='scheduler.player', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'кэш статистики Overwatch',
                'verbose_name_plural': 'кэш статистики Overwatch',
                'ordering': ['player__sort_order', 'overfast_player_id', 'mode'],
                'constraints': [models.UniqueConstraint(fields=('player', 'mode'), name='unique_overwatch_stats_cache_player_mode')],
            },
        ),
    ]
