# Generated by Django 5.2.13 on 2026-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_overwatchstatscache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overwatchstatscache',
            name='mode',
            field=models.CharField(choices=[('competitive', 'Competitive')], max_length=20, verbose_name='режим'),
        ),
    ]
